# Generated by Django 3.0.7 on 2020-08-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('json_serve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiod',
            name='real_name',
            field=models.TextField(max_length=50),
        ),
    ]
